"""Configuration for deterministic expression-box grouping."""

from __future__ import annotations

EXPRESSION_BOX_DESIGNS_SCHEMA_VERSION = "expression_box_designs.v1"
GROUPING_ALGORITHM_VERSION = "expression_box_grouping.v1"
EXPRESSION_PARTS_DESIGNS_SCHEMA_VERSION = "expression_parts_designs.v3"
PARTS_RECOMMENDATION_ALGORITHM_VERSION = "expression_parts_recommendation.v3.0.0"

EXPRESSION_PARTS_COLLECTION = "expression_parts_v3"
MILVUS_QUERY_LIMIT = 512
MILVUS_TIMEOUT_SECONDS = 20.0
RBS_SHORTLIST_PER_STRENGTH = 12
RBS_CONTEXT_CDS_PREFIX_NT = 90
RBS_CONTEXT_PREVIOUS_CDS_SUFFIX_NT = 35

DEFAULT_EXPRESSION_PARTS_DESIGN_COUNT = 12
MIN_EXPRESSION_PARTS_DESIGN_COUNT = 3
MAX_EXPRESSION_PARTS_DESIGN_COUNT = 96
EXPRESSION_PARTS_CANDIDATE_POOL_MIN = 256
EXPRESSION_PARTS_CANDIDATE_POOL_MULTIPLIER = 20
EXPRESSION_PARTS_CANDIDATE_POOL_MAX = 4096
EXPRESSION_SUCCESS_MIN_SCORE = 70.0
EXPRESSION_SUCCESS_EVIDENCE_WEIGHT = 30.0
EXPRESSION_SUCCESS_PROMOTER_WEIGHT = 25.0
EXPRESSION_SUCCESS_TRANSLATION_WEIGHT = 30.0
EXPRESSION_SUCCESS_TERMINATOR_WEIGHT = 10.0
EXPRESSION_SUCCESS_ASSEMBLY_WEIGHT = 5.0

BALANCED_MAX_MAIN_UNITS_PER_CASSETTE = 2
COMPACT_MAX_PROTEINS = 6
COMPACT_MAX_CDS_LENGTH_NT = 12_000


__all__ = [
    "BALANCED_MAX_MAIN_UNITS_PER_CASSETTE",
    "COMPACT_MAX_CDS_LENGTH_NT",
    "COMPACT_MAX_PROTEINS",
    "DEFAULT_EXPRESSION_PARTS_DESIGN_COUNT",
    "EXPRESSION_PARTS_CANDIDATE_POOL_MAX",
    "EXPRESSION_PARTS_CANDIDATE_POOL_MIN",
    "EXPRESSION_PARTS_CANDIDATE_POOL_MULTIPLIER",
    "EXPRESSION_BOX_DESIGNS_SCHEMA_VERSION",
    "EXPRESSION_PARTS_COLLECTION",
    "EXPRESSION_PARTS_DESIGNS_SCHEMA_VERSION",
    "EXPRESSION_SUCCESS_ASSEMBLY_WEIGHT",
    "EXPRESSION_SUCCESS_EVIDENCE_WEIGHT",
    "EXPRESSION_SUCCESS_MIN_SCORE",
    "EXPRESSION_SUCCESS_PROMOTER_WEIGHT",
    "EXPRESSION_SUCCESS_TERMINATOR_WEIGHT",
    "EXPRESSION_SUCCESS_TRANSLATION_WEIGHT",
    "GROUPING_ALGORITHM_VERSION",
    "MILVUS_QUERY_LIMIT",
    "MILVUS_TIMEOUT_SECONDS",
    "MAX_EXPRESSION_PARTS_DESIGN_COUNT",
    "MIN_EXPRESSION_PARTS_DESIGN_COUNT",
    "PARTS_RECOMMENDATION_ALGORITHM_VERSION",
    "RBS_CONTEXT_CDS_PREFIX_NT",
    "RBS_CONTEXT_PREVIOUS_CDS_SUFFIX_NT",
    "RBS_SHORTLIST_PER_STRENGTH",
]
